### ISSUE TITLE
Update DESCRIPTION bookdown #171: Commit e651470 Failing.

### ISSUE THREAD

**Issue by Jishan13** [jtr13/cc22tt#105]
Can anyone look into this? I am not sure why is it missing that package. I did include it.

**Comment by jl6298** [comment]
Hi, I didn't spot tm in our DESCRIPTION file. Are you sure you included it?

**Comment by Jishan13** [comment]
I was just coming to close this as Widyr was done, and I was working on including tm

**Comment by Jishan13** [comment]
Issue still persists

**Comment by jl6298** [comment]
How about we comment this one out and merge other prs first?

**Comment by Jishan13** [comment]
![image](https://user-images.githubusercontent.com/22248465/202608615-aed62b00-1d5d-44f6-9314-0744e41885da.png)

**Comment by Jishan13** [comment]
@jl6298 yeah let's try that

**Comment by Jishan13** [comment]
@naishadhparmar @shubhambhalala  @jl6298  do you guys know to resolve the error for #186, if not we can highlight it to the professor, and I can comment it in the mean time.

**Comment by jl6298** [comment]
Sorry, I have no idea what's going on [palmface].

**Comment by Jishan13** [comment]
@jtr13 Professor, can you please have a look at this error?https://github.com/jtr13/cc22tt/actions/runs/3493997924/jobs/5849381534

**Comment by jtr13** [comment]
No idea either but just tried re-running the job. When it's a bizarre, incomprehensible error that often works. 🤞

**Comment by jtr13** [comment]
The setup-r-dependencies is now working (I made some changes to the GitHub Actions workflow which may have helped or it may have solved itself) but now the twitter package is failing. It seems that the code needs an API token to run.

**Comment by jtr13** [comment]
I'm going to close this and open a new issue explaining the new problem.
