### ISSUE TITLE
twitter_scrape_nlp.Rmd not compiling

### ISSUE THREAD

**Issue by jtr13** [jtr13/cc22tt#114]
The problem is that the Google credentials are not set up to be able to use `googlesheets4`. I think it can be solved by

1. making the Google Sheet public

OR

2. adding the Google credentials in a way that will work in a non-interactive session (see here: https://github.com/jtr13/cc22tt/actions/runs/3506399144/jobs/5873415921#step:7:64)

OR 

3. reverting back to pulling the Twitter data directly (I already set up a Twitter API in GitHub actions since I thought that was the problem when in fact it was not.)

@russorenato  can you help with this?

In the meantime, I will comment `twitter_scrape_nlp.Rmd` out of `_bookdown.yml`.

**Comment by russorenato** [comment]
Hi Joyce and team.
Thanks for the comments.
Sorry, my fault. I changed the file and forgot to update the sharing
settings. The sheet should be publicly accessible now.

Thanks for your understanding.
Best,

*Renato Russo (he, him, his), Ed.D. Student*

Instructional Technology and Media
*, Teachers College Columbia University*


*--*

*Columbia University is built on the lands of the Lenape nation*

*russo.work <http://russo.work>*


*LinkedIn <https://www.linkedin.com/in/renatofarusso/>, Twitter
<http://twitter.com/renrusso/>*

**Comment by jtr13** [comment]
No worries! Making progress but there's an interactive piece that's causing it to fail:
https://github.com/jtr13/cc22tt/actions/runs/3509821857/jobs/5879181764#step:7:69
@russorenato can you submit a pull request to fix it? Thx.
Ask if anything isn't clear.

**Comment by russorenato** [comment]
Ok, fixing it now.
Thanks!
*Renato Russo (he, him, his), Ed.D. Student*

Instructional Technology and Media
*, Teachers College Columbia University*


*--*

*Columbia University is built on the lands of the Lenape nation*

*russo.work <http://russo.work>*


*LinkedIn <https://www.linkedin.com/in/renatofarusso/>, Twitter
<http://twitter.com/renrusso/>*

**Comment by russorenato** [comment]
Quick question: the instructions say that "the new commits will be added to
your pull request; *you do not need to, and should not, create a new pull
request.*" However, it seems that my pull request has been closed (when I
search for my open pull requests, no results match my search).
I'm sorry if I'm missing something, and I appreciate support on this.
Best,


[image: Screen Shot 2022-11-20 at 7.31.08 PM.png]

**Comment by jtr13** [comment]
Sorry that's only true before the pull request is merged. At this point you should open a new one. If it's a simple fix you can do it right on GitHub. Go to this file: https://github.com/jtr13/cc22tt/blob/main/twitter_scrape_nlp.Rmd click the edit (pen icon) button, make the changes, click the Propose changes button at the bottom and then follow the steps to create a pull request.

**Comment by jtr13** [comment]
Btw, I can't view the screenshot but in general it's more helpful to have a link to the page you're trying to show rather than a screenshot.

**Comment by russorenato** [comment]
Ok, thanks for the clarification.
I edited it right on GitHub. I think that commenting line 66 is sufficient.
Then, I went ahead and created the new pull request.
And thanks for the instructions for the screenshot, too!


*Renato Russo (he, him, his), Ed.D. Student*

Instructional Technology and Media
*, Teachers College Columbia University*


*--*

*Columbia University is built on the lands of the Lenape nation*

*russo.work <http://russo.work>*


*LinkedIn <https://www.linkedin.com/in/renatofarusso/>, Twitter
<http://twitter.com/renrusso/>*

**Comment by jtr13** [comment]
Hmm, that didn't work. The problem is in lines 354-362, see: https://github.com/jtr13/cc22tt/actions/runs/3511703653/jobs/5882716395#step:7:65

**Comment by russorenato** [comment]
Oh, I see. I think that's because the creators of the dictionary used in
that chunk ("nrc") included a prompt about copyright (one has to choose "1:
Yes" in order to have access to it. I saw that in the first time that I ran
the command, but never again.
I'll see if I can replace that with other dictionaries. If that does not
work, I'll think of alternatives.

Thanks

**Comment by jtr13** [comment]
Of course, no rush. In the meantime I will temporarily take out the chapter.

**Comment by russorenato** [comment]
Great, thanks!

**Comment by russorenato** [comment]
I fixed that part and created a new pull request. I think it will work now.

**Comment by jtr13** [comment]
Sorry I missed this... it's working now!

https://jtr13.github.io/cc22tt/twitter-textual-data-scraping-and-analyzing.html
