### ISSUE TITLE
fail to compile #194

### ISSUE THREAD

**Issue by jl6298** [jtr13/cc22tt#115]
Could someone take a look at action #194? it seems that there is an error in a certain chunk in "Interactive_3D_Vis.Rmd". I will comment "Interactive_3D_Vis.Rmd" out just for now.

**Comment by Jishan13** [comment]
@jl6298 this is not yet resolved right?

**Comment by jl6298** [comment]
Yes.

**Comment by Jishan13** [comment]
Yeah, It looked like their chunk was resulting into an issue... By any chance, did you try that in your local if it ran fine? or causing the same error?

**Comment by Jishan13** [comment]
@jl6298  Even this looks an an issue on their part right? For request #236?

**Comment by jtr13** [comment]
The problem was multiple code chunks with the same label. It's working now:

https://jtr13.github.io/cc22tt/interactive-3d-visualization-in-r.html
