### ISSUE TITLE
Error: path for html_dependency not found

### ISSUE THREAD

**Issue by zcysxy** [jtr13/cc22tt#24]
In two runs [#51](https://github.com/jtr13/cc22tt/actions/runs/3453149702) and [#52](https://github.com/jtr13/cc22tt/actions/runs/3453149702), `Error: path for html_dependency not found` appeared. I tried to remove the cache by setting `cache = FALSE` in `_common.R` but with no luck.

**Comment by shubhambhalala** [comment]
If it's not resolved, clone the repo of the submission, try it on your local, you might see the actual error in that process, be it of package or mentioning remote repo but if it is something related to the code, you can ask the student to look into it with the error.

**Comment by zcysxy** [comment]
Thanks for the reply @shubhambhalala! I followed your suggestion and located the error https://github.com/jtr13/cc22tt/blob/3fce0b96499730709f768a3434c7d33f90ad38b6/a_summary_of_interactive_chart.Rmd#L192-L203

It's because package `leaflet` puts html dependencies in a temp folder. But in [`_bookdown.yml`, `new_session` was set to true](https://github.com/jtr13/cc22tt/blob/3fce0b96499730709f768a3434c7d33f90ad38b6/_bookdown.yml#L2), which means each chapter will be rendered in a new session. So the html dependencies generated by `leaflet` are removed in the new sessions.

Two workarounds:

1. Set `eval=FALSE` for codeblocks containing `leaflet`
2. Set `new_session = false` in `_bookdown.yml`

I temporarily set `new_session = false` and the site was successfully deployed. Feel free to change it back if it is not appropriate.

## Reference

- https://bookdown.org/yihui/bookdown/new-session.html
- https://github.com/rstudio/bookdown/issues/15#issuecomment-573776659
- https://github.com/rstudio/bookdown/issues/1339

**Comment by jtr13** [comment]
Good work everyone! It seems that this is a new problem as we've used leaflet before with `new_session: true` and didn't have a problem:

https://jtr13.github.io/cc21/up-and-running-quickly-with-leaflet.html
https://github.com/jtr13/cc21/blob/main/_bookdown.yml

Hopefully it won't cause a problem to set `new_session` to `FALSE`.  We've run into problems in the past when content of some chapters conflicted with content of others. We can deal with that if it happens.

**Comment by shubhambhalala** [comment]
Way to go.. Cheers @zcysxy !

**Comment by zcysxy** [comment]
@jtr13 @shubhambhalala thanks for the reply! Sorry for the bad news that because of issue #34, I have to take out `a_summary_of_interactive_chart.Rmd` again, and I reverted `new_session` to `true` again. But at least we know how to deal with this issue now.

**Comment by jtr13** [comment]
Strange things happen with GitHub Actions... sometimes it fails, I click "Re-run job" and it works! I should note that if the error occurs in one of the "setup" sections it's not related to the content of the chapter. I'll take a look and see if I can figure out what's going on.

**Comment by jtr13** [comment]
I created a sample repo in case anyone wants to practice without worrying about affecting the rest of the project. Let me know if you'd like to be added as a collaborator on that site: [jtr13.github.io/ccsandbox/](https://jtr13.github.io/ccsandbox/)

**Comment by zcysxy** [comment]
> I created a sample repo in case anyone wants to practice without worrying about affecting the rest of the project. Let me know if you'd like to be added as a collaborator on that site: [jtr13.github.io/ccsandbox/](https://jtr13.github.io/ccsandbox/)

Great, thank you!

**Comment by jtr13** [comment]
Does anyone know how the `Error: path for html_dependency not found` problem was solved even after setting `new_session` back to `true`? I see that `leaflet` is working in this chapter: https://jtr13.github.io/cc22tt/geo-mapping-coordinate-extraction-using-api-calls.html I'm asking since we're running into the same problem in the other section.

**Comment by zcysxy** [comment]
Hi professor @jtr13, not the entire package of `leaflet` will cause this error. In [a_summary_of_interactive_chart.Rmd](https://github.com/jtr13/cc22tt/blob/main/a_summary_of_interactive_chart.Rmd), it's the function `addProviderTiles` in `leaflet` that cause the error.

**Comment by jtr13** [comment]
Good to know... thanks!
