### ISSUE TITLE
Error: <callr_remote_error: subscript out of bounds>

### ISSUE THREAD

**Issue by zcysxy** [jtr13/cc22tt#34]
This is so strange, **same commit**, the [first attempt](https://github.com/jtr13/cc22tt/actions/runs/3456673618/attempts/1) succeeded, but the [second](https://github.com/jtr13/cc22tt/actions/runs/3456673618/attempts/2) failed 😵‍💫

<img width="622" alt="image" src="https://user-images.githubusercontent.com/48207708/201544114-b0478afd-e8ac-4eca-89f3-27c9b550c624.png">

Seems like it is caused by `Remotes` packages (see https://github.com/r-lib/actions/issues/534).

**Comment by zcysxy** [comment]
Attempt 3 works again 😵‍💫. I will do more investigation later

**Comment by shubhambhalala** [comment]
after adding relevant remotes and packages this has been resolved but the html path error is occurring again. [Link](https://github.com/jtr13/cc22tt/actions/runs/3472246190)

**Comment by zcysxy** [comment]
@shubhambhalala Yeah, I'm afraid we need to set `new_session = FALSE` to solve the html dependencies issue. But as the professor said:

> We've run into problems in the past when content of some chapters conflicted with content of others.

So maybe we can deal with this issue after we have merged other pull requests.

cc @naishadhparmar
